# Chapter 11 Training Deep Neural Networks
### 11.1 The Vanishing/Exploding Gradients Problems

In [1]:
import tensorflow as tf

physical_devices = tf.config.list_physical_devices("GPU")
for device in physical_devices:
    tf.config.experimental.set_memory_growth(device, True)

### Fetch data

In [2]:
import pandas as pd
from sklearn.datasets import fetch_openml

mnist = fetch_openml("mnist_784", version=1)
X, y = mnist["data"], mnist["target"]

### Explore data

In [3]:
X.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
y.head()

0    5
1    0
2    4
3    1
4    9
Name: class, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [5]:
X = X.values
y = y.values

In [6]:
X[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
y[:5]

['5', '0', '4', '1', '9']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [8]:
X.shape

(70000, 784)

In [9]:
y.shape

(70000,)

__visualize data__

skipped

### Prepare data

__Normalize data__

In [10]:
X_norm = X / 255

In [11]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
y_onehot = lb.fit_transform(y)

__Split data__

In [12]:
from sklearn.model_selection import train_test_split

X_train_valid, X_test, y_train_valid, y_test = train_test_split(
    X_norm, y_onehot, test_size=0.2, random_state=42
)

In [13]:
X_train_valid.shape

(56000, 784)

In [14]:
X_test.shape

(14000, 784)

In [15]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_valid, y_train_valid, test_size=0.2, random_state=42
)

In [16]:
X_train.shape

(44800, 784)

In [17]:
X_valid.shape

(11200, 784)

### Shortlist promising models

In [18]:
from tensorflow import keras


def create_model(activation="relu", kernel_initializer="glorot_uniform"):
    model = keras.Sequential(
        [
            keras.layers.InputLayer(input_shape=(28 * 28)),
            keras.layers.BatchNormalization(),
            keras.layers.Dense(
                300,
                activation=activation,
                kernel_initializer=kernel_initializer,
                use_bias=False,
            ),
            keras.layers.BatchNormalization(),
            keras.layers.Dense(
                100,
                activation=activation,
                kernel_initializer=kernel_initializer,
                use_bias=False,
            ),
            keras.layers.BatchNormalization(),
            keras.layers.Dense(10, activation="softmax"),
        ]
    )
    model.compile(optimizer="adam", loss="categorical_crossentropy", metrics="acc")
    return model


models = [
    create_model(),
    create_model("elu", "he_normal"),
    create_model("selu", kernel_initializer="lecun_normal"),
]

models[0].summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 784)               3136
_________________________________________________________________
dense (Dense)                (None, 300)               235200
_________________________________________________________________
batch_normalization_1 (Batch (None, 300)               1200
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30000
_________________________________________________________________
batch_normalization_2 (Batch (None, 100)               400
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010
=================================================================
Total params: 270,946
Trainable params: 268,578
Non-trainable params: 2,368
_________________________________________________________________

In [19]:
import numpy as np
from sklearn.model_selection import KFold

n_models = len(models)
n_splits = 5
scores = np.zeros((n_splits, n_models))

kf = KFold(n_splits=n_splits)
for i_split, (ids_train, ids_valid) in enumerate(
    kf.split(X_train_valid, y_train_valid)
):
    for i_model, model in enumerate(models):
        history = model.fit(
            X_train_valid[ids_train],
            y_train_valid[ids_train],
            epochs=1000,
            callbacks=[keras.callbacks.EarlyStopping(patience=10)],
            validation_data=(X_train_valid[ids_valid], y_train_valid[ids_valid]),
        )
        scores[i_split, i_model] = model.evaluate(
            X_train_valid[ids_valid], y_train_valid[ids_valid]
        )[1]

df_scores = pd.DataFrame(data=scores, columns=["relu", "elu", "selu"])

Epoch 1/1000
1400/1400 [==============================] - 5s 3ms/step - loss: 0.3776 - acc: 0.8853 - val_loss: 0.1348 - val_acc: 0.9611
Epoch 2/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.1177 - acc: 0.9623 - val_loss: 0.1064 - val_acc: 0.9696
Epoch 3/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0839 - acc: 0.9746 - val_loss: 0.1025 - val_acc: 0.9697
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0644 - acc: 0.9801 - val_loss: 0.1092 - val_acc: 0.9708
Epoch 5/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0542 - acc: 0.9824 - val_loss: 0.1080 - val_acc: 0.9721
Epoch 6/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0452 - acc: 0.9854 - val_loss: 0.0874 - val_acc: 0.9767
Epoch 7/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0375 - acc: 0.9873 - val_loss: 0.0958 - val_acc: 0.9754
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0367 - acc: 0.9877 - val_loss: 0.1150 - val_acc: 0.9744
Epoch 9/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0292 - acc: 0.9903 - val_loss: 0.1062 - val_acc: 0.9737
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0304 - acc: 0.9896 - val_loss: 0.1179 - val_acc: 0.9739
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0252 - acc: 0.9916 - val_loss: 0.1192 - val_acc: 0.9759
Epoch 12/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0232 - acc: 0.9918 - val_loss: 0.1125 - val_acc: 0.9769
Epoch 13/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0222 - acc: 0.9927 - val_loss: 0.1060 - val_acc: 0.9765
Epoch 14/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0213 - acc: 0.9932 - val_loss: 0.1148 - val_acc: 0.9746
Epoch 15/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0185 - acc: 0.9941 - val_loss: 0.1010 - val_acc: 0.9766
Epoch 16/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0174 - acc: 0.9936 - val_loss: 0.1033 - val_acc: 0.9764
350/350 [==============================] - 0s 1ms/step - loss: 0.1033 - acc: 0.9764
Epoch 1/1000
1400/1400 [==============================] - 4s 2ms/step - loss: 0.3822 - acc: 0.8801 - val_loss: 0.1319 - val_acc: 0.9595
Epoch 2/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.1226 - acc: 0.9629 - val_loss: 0.1114 - val_acc: 0.9671
Epoch 3/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0811 - acc: 0.9745 - val_loss: 0.1031 - val_acc: 0.9696
Epoch 4/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0640 - acc: 0.9789 - val_loss: 0.0986 - val_acc: 0.9738
Epoch 5/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0507 - acc: 0.9830 - val_loss: 0.0973 - val_acc: 0.9739
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0437 - acc: 0.9860 - val_loss: 0.0968 - val_acc: 0.9738
Epoch 7/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0346 - acc: 0.9886 - val_loss: 0.0959 - val_acc: 0.9746
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0304 - acc: 0.9898 - val_loss: 0.0999 - val_acc: 0.9760
Epoch 9/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0303 - acc: 0.9894 - val_loss: 0.0922 - val_acc: 0.9755
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0236 - acc: 0.9918 - val_loss: 0.1148 - val_acc: 0.9749
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0214 - acc: 0.9934 - val_loss: 0.0986 - val_acc: 0.9785
Epoch 12/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0236 - acc: 0.9916 - val_loss: 0.0956 - val_acc: 0.9793
Epoch 13/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0194 - acc: 0.9938 - val_loss: 0.1079 - val_acc: 0.9756
Epoch 14/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0193 - acc: 0.9941 - val_loss: 0.1024 - val_acc: 0.9779
Epoch 15/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0143 - acc: 0.9951 - val_loss: 0.1112 - val_acc: 0.9769
Epoch 16/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0191 - acc: 0.9931 - val_loss: 0.1108 - val_acc: 0.9758
Epoch 17/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0170 - acc: 0.9940 - val_loss: 0.1050 - val_acc: 0.9780
Epoch 18/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0147 - acc: 0.9952 - val_loss: 0.1239 - val_acc: 0.9754
Epoch 19/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0180 - acc: 0.9938 - val_loss: 0.1102 - val_acc: 0.9754
350/350 [==============================] - 0s 1ms/step - loss: 0.1102 - acc: 0.9754
Epoch 1/1000
1400/1400 [==============================] - 4s 2ms/step - loss: 0.3928 - acc: 0.8781 - val_loss: 0.1576 - val_acc: 0.9544
Epoch 2/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.1369 - acc: 0.9584 - val_loss: 0.1198 - val_acc: 0.9655
Epoch 3/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0891 - acc: 0.9726 - val_loss: 0.1156 - val_acc: 0.9657
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0685 - acc: 0.9775 - val_loss: 0.1036 - val_acc: 0.9700
Epoch 5/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0583 - acc: 0.9818 - val_loss: 0.0983 - val_acc: 0.9733
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0462 - acc: 0.9856 - val_loss: 0.1073 - val_acc: 0.9725
Epoch 7/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0451 - acc: 0.9848 - val_loss: 0.0915 - val_acc: 0.9744
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0349 - acc: 0.9879 - val_loss: 0.1122 - val_acc: 0.9721
Epoch 9/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0310 - acc: 0.9902 - val_loss: 0.0999 - val_acc: 0.9754
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0275 - acc: 0.9912 - val_loss: 0.1105 - val_acc: 0.9759
Epoch 11/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0265 - acc: 0.9911 - val_loss: 0.1014 - val_acc: 0.9757
Epoch 12/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0240 - acc: 0.9916 - val_loss: 0.1203 - val_acc: 0.9726
Epoch 13/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0225 - acc: 0.9929 - val_loss: 0.0966 - val_acc: 0.9772
Epoch 14/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0208 - acc: 0.9929 - val_loss: 0.1003 - val_acc: 0.9777
Epoch 15/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0192 - acc: 0.9939 - val_loss: 0.1052 - val_acc: 0.9779
Epoch 16/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0199 - acc: 0.9930 - val_loss: 0.1276 - val_acc: 0.9754
Epoch 17/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0172 - acc: 0.9942 - val_loss: 0.1197 - val_acc: 0.9736
350/350 [==============================] - 0s 754us/step - loss: 0.1197 - acc: 0.9736
Epoch 1/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0437 - acc: 0.9877 - val_loss: 0.0139 - val_acc: 0.9964
Epoch 2/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0262 - acc: 0.9911 - val_loss: 0.0198 - val_acc: 0.9946
Epoch 3/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0228 - acc: 0.9926 - val_loss: 0.0173 - val_acc: 0.9951
Epoch 4/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0198 - acc: 0.9934 - val_loss: 0.0280 - val_acc: 0.9913
Epoch 5/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0165 - acc: 0.9946 - val_loss: 0.0196 - val_acc: 0.9937
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0194 - acc: 0.9933 - val_loss: 0.0225 - val_acc: 0.9924
Epoch 7/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0169 - acc: 0.9943 - val_loss: 0.0205 - val_acc: 0.9937
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0168 - acc: 0.9944 - val_loss: 0.0304 - val_acc: 0.9912
Epoch 9/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0146 - acc: 0.9954 - val_loss: 0.0318 - val_acc: 0.9922
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0134 - acc: 0.9954 - val_loss: 0.0340 - val_acc: 0.9911
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0150 - acc: 0.9951 - val_loss: 0.0360 - val_acc: 0.9894
350/350 [==============================] - 0s 760us/step - loss: 0.0360 - acc: 0.9894
Epoch 1/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0404 - acc: 0.9883 - val_loss: 0.0096 - val_acc: 0.9968
Epoch 2/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0221 - acc: 0.9928 - val_loss: 0.0100 - val_acc: 0.9970
Epoch 3/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0195 - acc: 0.9935 - val_loss: 0.0145 - val_acc: 0.9962
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0186 - acc: 0.9939 - val_loss: 0.0172 - val_acc: 0.9953
Epoch 5/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0172 - acc: 0.9942 - val_loss: 0.0133 - val_acc: 0.9958
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0135 - acc: 0.9955 - val_loss: 0.0199 - val_acc: 0.9949
Epoch 7/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0141 - acc: 0.9950 - val_loss: 0.0221 - val_acc: 0.9944
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0150 - acc: 0.9949 - val_loss: 0.0206 - val_acc: 0.9930
Epoch 9/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0115 - acc: 0.9962 - val_loss: 0.0260 - val_acc: 0.9934
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0103 - acc: 0.9964 - val_loss: 0.0258 - val_acc: 0.9934
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0124 - acc: 0.9961 - val_loss: 0.0306 - val_acc: 0.9927
350/350 [==============================] - 0s 770us/step - loss: 0.0306 - acc: 0.9927
Epoch 1/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0425 - acc: 0.9881 - val_loss: 0.0141 - val_acc: 0.9964
Epoch 2/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0270 - acc: 0.9912 - val_loss: 0.0152 - val_acc: 0.9951
Epoch 3/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0214 - acc: 0.9934 - val_loss: 0.0147 - val_acc: 0.9950
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0203 - acc: 0.9932 - val_loss: 0.0191 - val_acc: 0.9939
Epoch 5/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0157 - acc: 0.9945 - val_loss: 0.0253 - val_acc: 0.9921
Epoch 6/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0172 - acc: 0.9940 - val_loss: 0.0277 - val_acc: 0.9918
Epoch 7/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0160 - acc: 0.9944 - val_loss: 0.0291 - val_acc: 0.9917
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0154 - acc: 0.9950 - val_loss: 0.0268 - val_acc: 0.9926
Epoch 9/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0157 - acc: 0.9950 - val_loss: 0.0296 - val_acc: 0.9923
Epoch 10/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0142 - acc: 0.9951 - val_loss: 0.0346 - val_acc: 0.9906
Epoch 11/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0142 - acc: 0.9951 - val_loss: 0.0382 - val_acc: 0.9896
350/350 [==============================] - 0s 748us/step - loss: 0.0382 - acc: 0.9896
Epoch 1/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0219 - acc: 0.9930 - val_loss: 0.0135 - val_acc: 0.9971
Epoch 2/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0155 - acc: 0.9950 - val_loss: 0.0236 - val_acc: 0.9950
Epoch 3/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0153 - acc: 0.9947 - val_loss: 0.0170 - val_acc: 0.9961
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0127 - acc: 0.9957 - val_loss: 0.0155 - val_acc: 0.9954
Epoch 5/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0136 - acc: 0.9958 - val_loss: 0.0185 - val_acc: 0.9968
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0125 - acc: 0.9957 - val_loss: 0.0214 - val_acc: 0.9955
Epoch 7/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0134 - acc: 0.9953 - val_loss: 0.0249 - val_acc: 0.9956
Epoch 8/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0095 - acc: 0.9970 - val_loss: 0.0297 - val_acc: 0.9947
Epoch 9/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0110 - acc: 0.9964 - val_loss: 0.0344 - val_acc: 0.9946
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0106 - acc: 0.9966 - val_loss: 0.0284 - val_acc: 0.9946
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0107 - acc: 0.9965 - val_loss: 0.0326 - val_acc: 0.9949
350/350 [==============================] - 0s 781us/step - loss: 0.0326 - acc: 0.9949
Epoch 1/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0186 - acc: 0.9940 - val_loss: 0.0184 - val_acc: 0.9967
Epoch 2/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0144 - acc: 0.9947 - val_loss: 0.0229 - val_acc: 0.9962
Epoch 3/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0127 - acc: 0.9956 - val_loss: 0.0225 - val_acc: 0.9968
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0113 - acc: 0.9961 - val_loss: 0.0206 - val_acc: 0.9976
Epoch 5/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0104 - acc: 0.9965 - val_loss: 0.0240 - val_acc: 0.9966
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0110 - acc: 0.9964 - val_loss: 0.0188 - val_acc: 0.9964
Epoch 7/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0118 - acc: 0.9959 - val_loss: 0.0214 - val_acc: 0.9958
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0108 - acc: 0.9964 - val_loss: 0.0177 - val_acc: 0.9965
Epoch 9/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0091 - acc: 0.9968 - val_loss: 0.0177 - val_acc: 0.9958
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0101 - acc: 0.9965 - val_loss: 0.0212 - val_acc: 0.9955
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0103 - acc: 0.9967 - val_loss: 0.0239 - val_acc: 0.9955
Epoch 12/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0096 - acc: 0.9971 - val_loss: 0.0234 - val_acc: 0.9961
Epoch 13/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0088 - acc: 0.9971 - val_loss: 0.0247 - val_acc: 0.9960
Epoch 14/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0079 - acc: 0.9975 - val_loss: 0.0301 - val_acc: 0.9952
Epoch 15/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0079 - acc: 0.9972 - val_loss: 0.0260 - val_acc: 0.9955
Epoch 16/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0087 - acc: 0.9973 - val_loss: 0.0314 - val_acc: 0.9946
Epoch 17/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0076 - acc: 0.9974 - val_loss: 0.0309 - val_acc: 0.9938
Epoch 18/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0077 - acc: 0.9976 - val_loss: 0.0429 - val_acc: 0.9933
Epoch 19/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0083 - acc: 0.9973 - val_loss: 0.0384 - val_acc: 0.9938
350/350 [==============================] - 0s 766us/step - loss: 0.0384 - acc: 0.9938
Epoch 1/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0213 - acc: 0.9934 - val_loss: 0.0079 - val_acc: 0.9981
Epoch 2/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0141 - acc: 0.9953 - val_loss: 0.0106 - val_acc: 0.9977
Epoch 3/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0139 - acc: 0.9955 - val_loss: 0.0160 - val_acc: 0.9964
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0142 - acc: 0.9952 - val_loss: 0.0078 - val_acc: 0.9980
Epoch 5/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0120 - acc: 0.9958 - val_loss: 0.0082 - val_acc: 0.9975
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0122 - acc: 0.9963 - val_loss: 0.0247 - val_acc: 0.9942
Epoch 7/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0120 - acc: 0.9960 - val_loss: 0.0198 - val_acc: 0.9958
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0115 - acc: 0.9962 - val_loss: 0.0230 - val_acc: 0.9944
Epoch 9/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0111 - acc: 0.9961 - val_loss: 0.0176 - val_acc: 0.9955
Epoch 10/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0096 - acc: 0.9968 - val_loss: 0.0204 - val_acc: 0.9946
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0108 - acc: 0.9961 - val_loss: 0.0233 - val_acc: 0.9948
Epoch 12/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0114 - acc: 0.9965 - val_loss: 0.0232 - val_acc: 0.9946
Epoch 13/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0096 - acc: 0.9969 - val_loss: 0.0254 - val_acc: 0.9941
Epoch 14/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0101 - acc: 0.9969 - val_loss: 0.0214 - val_acc: 0.9949
350/350 [==============================] - 0s 743us/step - loss: 0.0214 - acc: 0.9949
Epoch 1/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0180 - acc: 0.9941 - val_loss: 0.0070 - val_acc: 0.9982
Epoch 2/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0114 - acc: 0.9955 - val_loss: 0.0060 - val_acc: 0.9982
Epoch 3/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0102 - acc: 0.9968 - val_loss: 0.0102 - val_acc: 0.9968
Epoch 4/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0102 - acc: 0.9965 - val_loss: 0.0088 - val_acc: 0.9977
Epoch 5/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0091 - acc: 0.9968 - val_loss: 0.0097 - val_acc: 0.9979
Epoch 6/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0095 - acc: 0.9969 - val_loss: 0.0160 - val_acc: 0.9965
Epoch 7/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0098 - acc: 0.9968 - val_loss: 0.0125 - val_acc: 0.9971
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0094 - acc: 0.9969 - val_loss: 0.0173 - val_acc: 0.9963
Epoch 9/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0098 - acc: 0.9967 - val_loss: 0.0195 - val_acc: 0.9957
Epoch 10/1000
1400/1400 [==============================] - 2s 2ms/step - loss: 0.0095 - acc: 0.9969 - val_loss: 0.0165 - val_acc: 0.9965
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0088 - acc: 0.9969 - val_loss: 0.0204 - val_acc: 0.9952
Epoch 12/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0093 - acc: 0.9973 - val_loss: 0.0158 - val_acc: 0.9959

In [20]:
df_scores

       relu       elu      selu
0  0.976429  0.975357  0.973571
1  0.989375  0.992679  0.989643
2  0.994911  0.993839  0.994911
3  0.995893  0.996071  0.995714
4  0.995982  0.997500  0.995714

In [21]:
df_scores_mean_std = pd.DataFrame({"mean": df_scores.mean(), "std": df_scores.std()})
df_scores_mean_std

          mean       std
relu  0.990518  0.008335
elu   0.991089  0.008993
selu  0.989911  0.009479

__Train (the best) model__

In [22]:
model = create_model()
model.fit(
    X_train,
    y_train,
    epochs=1000,
    callbacks=[keras.callbacks.EarlyStopping(patience=10)],
    validation_data=(X_valid, y_valid),
)

Epoch 1/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.3840 - acc: 0.8819 - val_loss: 0.1379 - val_acc: 0.9593
Epoch 2/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.1181 - acc: 0.9634 - val_loss: 0.1044 - val_acc: 0.9681
Epoch 3/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0879 - acc: 0.9723 - val_loss: 0.1024 - val_acc: 0.9693
Epoch 4/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0672 - acc: 0.9778 - val_loss: 0.0911 - val_acc: 0.9727
Epoch 5/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0519 - acc: 0.9826 - val_loss: 0.0952 - val_acc: 0.9729
Epoch 6/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0451 - acc: 0.9853 - val_loss: 0.0891 - val_acc: 0.9745
Epoch 7/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0427 - acc: 0.9855 - val_loss: 0.0966 - val_acc: 0.9728
Epoch 8/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0357 - acc: 0.9888 - val_loss: 0.0872 - val_acc: 0.9762
Epoch 9/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0284 - acc: 0.9909 - val_loss: 0.0998 - val_acc: 0.9754
Epoch 10/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0323 - acc: 0.9892 - val_loss: 0.1020 - val_acc: 0.9751
Epoch 11/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0262 - acc: 0.9911 - val_loss: 0.1047 - val_acc: 0.9759
Epoch 12/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0217 - acc: 0.9921 - val_loss: 0.1061 - val_acc: 0.9760
Epoch 13/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0283 - acc: 0.9905 - val_loss: 0.1083 - val_acc: 0.9763
Epoch 14/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0205 - acc: 0.9935 - val_loss: 0.1027 - val_acc: 0.9779
Epoch 15/1000
1400/1400 [==============================] - 3s 2ms/step - loss: 0.0191 - acc: 0.9933 - val_loss: 0.1016 - val_acc: 0.9777
Epoch 16/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0205 - acc: 0.9923 - val_loss: 0.1073 - val_acc: 0.9772
Epoch 17/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0177 - acc: 0.9934 - val_loss: 0.1040 - val_acc: 0.9791
Epoch 18/1000
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0176 - acc: 0.9942 - val_loss: 0.1106 - val_acc: 0.9754

__Evaluate the model__

In [23]:
loss, acc = model.evaluate(X_test, y_test)

438/438 [==============================] - 1s 2ms/step - loss: 0.1205 - acc: 0.9754

__Use the model for prediction__

In [24]:
X_new = X_test[:5]
y_new = y_test[:5]

y_pred = model.predict(X_new)

In [25]:
np.argmax(y_new, axis=1)

array([8, 4, 8, 7, 7])

In [26]:
np.argmax(y_pred, axis=1)

array([8, 4, 8, 7, 7])

### Examine BN layer

In [27]:
[(var.name, var.trainable) for var in model.layers[0].variables]

[('batch_normalization_9/gamma:0', True),
 ('batch_normalization_9/beta:0', True),
 ('batch_normalization_9/moving_mean:0', False),
 ('batch_normalization_9/moving_variance:0', False)]

In [28]:
model.layers[0].updates

/home/yu/anaconda3/envs/data-science/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py:1402: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`layer.updates` will be removed in a future version. '

[]